targets:
  $default:
    builders:
      reflectable:
        generate_for:
          exclude:
            - test/**/Matcher_test.dart
          include:
            - test/**_test.dart
        options:
          formatted: true