name: objectvalidator
version: 2.0.0

author: Mike Mitterer <office@mikemitterer.at>
description: Object validation library
homepage: https://github.com/MikeMitterer/objectvalidator.dart

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:

  matcher: ^0.12.0

  logging: '>=0.11.3 <1.0.0'

  validate: ^1.0.0

  l10n: '>=2.0.15 <3.0.0'
    # git: git@github.com:MikeMitterer/dart-l10n-gettext.git
    # path: /Volumes/Daten/DevLocal/DevDart/L10N4Dart

dev_dependencies:
  test: any

  console_log_handler: ^1.0.0
    # git: git@github.com:MikeMitterer/dart-console_log_handler.git
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  build_runner: any
  build_test: any
  build_web_compilers: any
