name: beanvalidator

dependencies:
  browser: any

  matcher: ">=0.10.1+1 <0.11.0"

  logging: any
  logging_handlers: any

  console_log_handler:
    path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: any

dev_dependencies:

  unittest: any