name: beanvalidator
version: 0.1.0

dependencies:
  browser: any

  matcher: ">=0.10.1+1 <0.11.0"

  logging: ">=0.9.2 <0.10.0"
  logging_handlers: ">=0.8.0 <0.9.0"

  console_log_handler:
    path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: any

  l10n:
    path: /Volumes/Daten/DevLocal/DevDart/L10N

dev_dependencies:

  unittest: any
