name: beanvalidator
version: 0.1.1

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  browser: '^0.10.0'

  matcher: '^0.12.0'

  logging: ^0.11.0
  console_log_handler: ^0.4.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  validate: '^1.0.0'

  l10n: 1.2.2
   # path: /Volumes/Daten/DevLocal/DevDart/L10N4Dart

  reflectable: '^1.0.0'

dev_dependencies:
  grinder: 'any'
  test: 'any'
