name: validate_sample
version: 0.0.1
description: Material Design Lite 'MDL Article Template'
author: <Mike Mitterer> <office@mikemitterer.at>
#homepage: https://www.example.com

environment:
  sdk: '>=1.12.0 <2.0.0'

dependencies:
  browser: '^0.10.0'

  mdl: # '^2.0.0'
    path: /Volumes/Daten/DevLocal/DevDart/MaterialDesignLite


  logging: ^0.11.0
  logging_handlers: ^0.8.0
  console_log_handler: ^0.2.0
    # path: /Volumes/Daten/DevLocal/DevDart/ConsoleLogHandler

  dice: ^1.7.0

  reflectable: '^1.0.0'

  beanvalidator:
    path: '../../'

  dart_to_js_script_rewriter: ^0.1.0
  
transformers:
  - dart_to_js_script_rewriter

  - reflectable:
      entry_points:
        - web/main.dart # The path to your main file
#      formatted: true # Optional.
